name: Ruby on Rails test routine

on:
  push:
    branches:
      - 'main'
      - 'dev'
  pull_request:
    branches:
      - 'main'

jobs:
  test-suite:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: "0"
    - name: install Lando
      run: |
        wget https://files.lando.dev/installer/lando-x64-stable.deb
        sudo dpkg --ignore-depends=docker-ce -i lando-x64-stable.deb
    - name: Report versions
      run: |
        docker version
        lando version
        node -v
        yarn -v
    - name: get user ids
      run: |
        ls -al .
        whoami
        id
        id -u
        id -g
        getent group $(id -g)
        groups
    - name: Pull all images
      run: |
        docker compose pull --ignore-pull-failures
    - name: Install test harness
      run: |
        yarn add leia-parser mocha chai@4 command-line-test
    - name: Generate test files
      run: |
        yarn leia "TESTING*.md" test -r 2 -s 'Start up tests' -t 'Verification commands' -c 'Destroy tests' --split-file
    - name: Run docker compose tests
      run: |
        yarn mocha --timeout 900000 test/*compose*.func.js 
